My Code Won't Work help
DarthCoursucant/Real-Estate-Agency-1 pull request #2
Opened 2024-06-15 21:31 UTC by DarthCoursucant

2024-06-15 21:46 UTC, werivik requested changes
Du har for det meste skrive feil her og der, jeg har point'et ut noen av de, men tror det er flere som jeg klarer kanskje ikke i finne. Prøv å se gjennom koden mer nøye, add "/" der det trengs. På CSS så er det også noen skrive/navn feil, og du burde kanskje prøve å bruke class names istedenfor id's hvis mulig

2024-06-15 21:46 UTC, werivik commented on html-files/construction.html
> +        <li>
koden vil ikke funke på grunn av at elementet har ikke et "/" på slutten

2024-06-15 21:46 UTC, werivik commented on html-files/construction.html
> +            <input type="text" id="name" name="user_name"/>
unødvending "/" på slutten, tror det funker helt fint som dette: "<input type="text" id="name" name="user_name">"

2024-06-15 21:46 UTC, werivik commented on html-files/construction.html
> +        <yi>
skrivefeil? <yi> burde være <li> istedenfor, hvis du endrer det så burde koden funke

2024-06-15 21:46 UTC, werivik commented on html-files/construction.html
for det meste ser jeg skrivefeil, hvis du fikser de så burde koden funke helt fint.

2024-06-15 21:46 UTC, werivik commented on css-files/wefssd.css
Jeg ser at du kalte css filen som tilhører construction.html som "wefssd.ss", for å ikke skape noen forvirringer ville jeg endre navnet til noe mer passende for den tilhørende HTML siden, som f.eks. "construction.css". Selve koden merket jeg noen skrive-/navn feil, tror det er derfor CSS vil ikke funke for deg :) Ville dobbel sjekke alle navnene og prøve å bruke hovedsakelig class names istedenfor id's hvis mulig.

2024-06-15 21:46 UTC, werivik commented on html-files/construction.html
> +    <ul>
Ops! glemte en "/" på linje 57, <ul> burde være </ul>

2024-06-16 10:02 UTC, DarthCoursucant commented
har endret det du nevnte, skal vi merge?

2024-06-16 11:56 UTC, DarthCoursucant commented
Made some changes something I should change ?

2024-06-16 12:20 UTC, werivik commented
fra det jeg ser så er all koden riktig skrevet, men jeg ser på designet at det er litt rotete?

2024-06-16 15:18 UTC, DarthCoursucant commented
har endret på de tingene som du sa, er det approved ?

2024-06-16 15:18 UTC, merged